package coursescheduler;

/** @author evilc */
public class AddCourseDepartmentChair extends javax.swing.JPanel {
  String page = "ADD_COURSE_DEPARTMENT_CHAIR";
  PanelManager controller;

  /** @param input */
  public void setController(PanelManager input) {
    controller = input;
  }

  /** @return */
  public String returnPage() {
    return page;
  }

  /** */
  public AddCourseDepartmentChair() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    addCoursePreview = new javax.swing.JTable();
    addCourseSubmitButton = new javax.swing.JButton();
    addCourseCancelButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    addCourseProfessorInput = new javax.swing.JTextField();
    addCourseIDInput = new javax.swing.JTextField();
    addCoruseRoomInput = new javax.swing.JTextField();
    addCourseTimesCombo = new javax.swing.JComboBox<>();
    addCourseDaysCombo = new javax.swing.JComboBox<>();
    addCourseCollegeCombo = new javax.swing.JComboBox<>();
    addCourseErrorDisplay1 = new javax.swing.JLabel();
    addCourseErrorCollege = new javax.swing.JLabel();
    addCourseErrorProfessor = new javax.swing.JLabel();
    addCourseErrorId = new javax.swing.JLabel();
    addCourseErrorName = new javax.swing.JLabel();
    addCourseErrorDays = new javax.swing.JLabel();
    addCourseErrorRoom = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    addCourseSeatsInput = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    addCourseNameInput = new javax.swing.JTextField();
    addCourseErrorSeats = new javax.swing.JLabel();
    addCourseErrorTimes = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel1.setText("Add Course");

    addCoursePreview.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {"College:", null},
              {"ID:", null},
              {"Name:", null},
              {"Professor:", null},
              {"Room(s):", null},
              {"Times:", null},
              {"Days:", null},
              {"Seats:", null}
            },
            new String[] {"Course Info", ""}) {
          boolean[] canEdit = new boolean[] {false, false};

          public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
          }
        });
    jScrollPane1.setViewportView(addCoursePreview);

    addCourseSubmitButton.setText("Submit");

    addCourseCancelButton.setText("Cancel");

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("College:");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("ID:");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel4.setText("Professor:");

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel5.setText("Room(s):");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel6.setText("Times:");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel7.setText("Days:");

    addCourseTimesCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Times"}));

    addCourseDaysCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Days"}));

    addCourseCollegeCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select College"}));

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel8.setText("Seats:");

    addCourseSeatsInput.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            addCourseSeatsInputActionPerformed(evt);
          }
        });

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel9.setText("Name:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(addCourseCancelButton)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(addCourseSubmitButton)
                                    .addGap(39, 39, 39))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jLabel7,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                53,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addComponent(
                                                                jLabel6,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                53,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addComponent(
                                                                jLabel5,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                53,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addComponent(
                                                                jLabel4,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                53,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addComponent(
                                                                jLabel3,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                53,
                                                                javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addGroup(
                                                                layout
                                                                    .createParallelGroup(
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.TRAILING,
                                                                        false)
                                                                    .addComponent(
                                                                        jLabel2,
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.LEADING,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                    .addComponent(
                                                                        jLabel1,
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.LEADING,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel9))
                                                    .addGap(59, 59, 59)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addComponent(addCourseNameInput)
                                                            .addComponent(addCourseProfessorInput)
                                                            .addComponent(addCourseIDInput)
                                                            .addComponent(addCoruseRoomInput)
                                                            .addComponent(
                                                                addCourseTimesCombo,
                                                                0,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                addCourseDaysCombo,
                                                                0,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                addCourseCollegeCombo,
                                                                0,
                                                                178,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                addCourseErrorDisplay1,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(addCourseSeatsInput))))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(
                                                        addCourseErrorCollege,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                        addCourseErrorProfessor,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                        addCourseErrorId,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                        addCourseErrorName,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                        addCourseErrorRoom,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(
                                                addCourseErrorDays,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                addCourseErrorSeats,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                addCourseErrorTimes,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap()))));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(
                                addCourseErrorDisplay1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                29,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseErrorCollege,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                19,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseCollegeCombo,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseErrorId,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                19,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseIDInput,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseNameInput,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        addCourseErrorProfessor,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        19,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        addCourseErrorRoom,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        19,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(
                                        jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        163,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addCourseSubmitButton)
                                            .addComponent(addCourseCancelButton))
                                    .addGap(4, 4, 4))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCourseProfessorInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCoruseRoomInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCourseTimesCombo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(
                                                addCourseErrorTimes,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                19,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCourseDaysCombo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(
                                                addCourseErrorDays,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                19,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCourseSeatsInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(
                                                addCourseErrorSeats,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                19,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(
                        addCourseErrorName,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        19,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(295, 335, Short.MAX_VALUE)));
  } // </editor-fold>//GEN-END:initComponents

  private void addCourseSeatsInputActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_addCourseSeatsInputActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_addCourseSeatsInputActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField addCoruseRoomInput;
  private javax.swing.JButton addCourseCancelButton;
  private javax.swing.JComboBox<String> addCourseCollegeCombo;
  private javax.swing.JComboBox<String> addCourseDaysCombo;
  private javax.swing.JLabel addCourseErrorCollege;
  private javax.swing.JLabel addCourseErrorDays;
  private javax.swing.JLabel addCourseErrorDisplay1;
  private javax.swing.JLabel addCourseErrorId;
  private javax.swing.JLabel addCourseErrorName;
  private javax.swing.JLabel addCourseErrorProfessor;
  private javax.swing.JLabel addCourseErrorRoom;
  private javax.swing.JLabel addCourseErrorSeats;
  private javax.swing.JLabel addCourseErrorTimes;
  private javax.swing.JTextField addCourseIDInput;
  private javax.swing.JTextField addCourseNameInput;
  private javax.swing.JTable addCoursePreview;
  private javax.swing.JTextField addCourseProfessorInput;
  private javax.swing.JTextField addCourseSeatsInput;
  private javax.swing.JButton addCourseSubmitButton;
  private javax.swing.JComboBox<String> addCourseTimesCombo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
