package coursescheduler;

/** @author evilc */
public class CourseSchedulerFrame extends javax.swing.JFrame {
  LoginPage loginPagePanel = new LoginPage();
  createAccountJpanel createAccountPanel = new createAccountJpanel();
  AddCourseDepartmentChair addCourseDepartmentChairPanel = new AddCourseDepartmentChair();
  AddCoursePageFaculty addCourseFacultyPanel = new AddCoursePageFaculty();
  DepartmentChairPage departmentChairPanel = new DepartmentChairPage();
  RegistrarPage registrarPanel = new RegistrarPage();
  EditCourse editCoursePanel = new EditCourse();
  FacultyPage facultyPanel = new FacultyPage();
  RemoveCoursePage removeCoursePanel = new RemoveCoursePage();

  PanelManager controller =
      new PanelManager(
          loginPagePanel,
          createAccountPanel,
          addCourseDepartmentChairPanel,
          addCourseFacultyPanel,
          editCoursePanel,
          registrarPanel,
          facultyPanel,
          departmentChairPanel,
          removeCoursePanel);

  /** Creates new form guiFrame */
  public CourseSchedulerFrame() {
    add(loginPagePanel);
    add(createAccountPanel);
    add(addCourseDepartmentChairPanel);
    add(addCourseFacultyPanel);
    add(departmentChairPanel);
    add(registrarPanel);
    add(editCoursePanel);
    add(facultyPanel);
    add(removeCoursePanel);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    debugCombo = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.FlowLayout());

    jLabel1.setText("DEBUG:");
    getContentPane().add(jLabel1);

    debugCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {
              "LOGIN",
              "CREATE_ACCOUNT",
              "ADD_COURSE_DEPARTMENT_CHAIR",
              "ADD_COURSE_FACULTY",
              "REMOVE_COURSE",
              "EDIT_COURSE",
              "SCHEDULE_GENERATOR",
              "INPUT_FILE",
              "DEPARTMENT_CHAIR",
              "FACULTY",
              "REGISTRAR"
            }));
    debugCombo.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            debugComboActionPerformed(evt);
          }
        });
    getContentPane().add(debugCombo);

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void debugComboActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_debugComboActionPerformed
    // TODO add your handling code here:
    String nextPage = debugCombo.getSelectedItem().toString();
    controller.switchPage("DEBUG", nextPage);
  } // GEN-LAST:event_debugComboActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> debugCombo;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
