package coursescheduler;

/** @author evilc */
public class EditCourse extends javax.swing.JPanel {
  String page = "EDIT_COURSE";
  PanelManager controller;

  public void setController(PanelManager input) {
    controller = input;
  }

  public String returnPage() {
    return page;
  }

  public EditCourse() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    addCoursePreview = new javax.swing.JTable();
    addCourseSubmitButton = new javax.swing.JButton();
    addCourseCancelButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    editCourseProfessorInput = new javax.swing.JTextField();
    editCourseIDInput = new javax.swing.JTextField();
    editCoruseRoomInput = new javax.swing.JTextField();
    editCourseTimesCombo = new javax.swing.JComboBox<>();
    editCourseDaysCombo = new javax.swing.JComboBox<>();
    editCourseCollegeCombo = new javax.swing.JComboBox<>();
    addCourseErrorDisplay1 = new javax.swing.JLabel();
    editCourseCollegeCombo1 = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    editCourseSeatsInput = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    addCourseError_Course = new javax.swing.JLabel();
    addCourseError_College = new javax.swing.JLabel();
    addCourseError_Professor = new javax.swing.JLabel();
    addCourseError_ID = new javax.swing.JLabel();
    addCourseError_Room = new javax.swing.JLabel();
    addCourseError_Times = new javax.swing.JLabel();
    addCourseError_Days = new javax.swing.JLabel();
    addCourseError_Seats = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    editCourseNameInput = new javax.swing.JTextField();
    addCourseError_Name = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel1.setText("Edit Course");

    addCoursePreview.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {"College:", null},
              {"ID:", null},
              {"Name:", null},
              {"Professor:", null},
              {"Room(s):", null},
              {"Times:", null},
              {"Days:", null},
              {"Seats:", null}
            },
            new String[] {"Course Info", ""}));
    jScrollPane1.setViewportView(addCoursePreview);

    addCourseSubmitButton.setText("Submit");

    addCourseCancelButton.setText("Cancel");

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("College:");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("ID:");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel4.setText("Professor:");

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel5.setText("Room(s):");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel6.setText("Times:");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel7.setText("Days:");

    editCourseTimesCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Times"}));

    editCourseDaysCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Days"}));

    editCourseCollegeCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select College"}));

    editCourseCollegeCombo1.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Course"}));

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel8.setText("Course:");

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel9.setText("Seats:");

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel11.setText("Name:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel1)
                    .addGap(0, 0, 0))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(addCourseCancelButton)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addComponent(addCourseSubmitButton))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        345,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING)
                                                            .addGroup(
                                                                layout
                                                                    .createSequentialGroup()
                                                                    .addComponent(
                                                                        jLabel2,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                    .addGap(1, 1, 1))
                                                            .addGroup(
                                                                layout
                                                                    .createSequentialGroup()
                                                                    .addComponent(
                                                                        jLabel8,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                    .addPreferredGap(
                                                                        javax.swing.LayoutStyle
                                                                            .ComponentPlacement
                                                                            .RELATED))
                                                            .addGroup(
                                                                layout
                                                                    .createSequentialGroup()
                                                                    .addGroup(
                                                                        layout
                                                                            .createParallelGroup(
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING)
                                                                            .addComponent(
                                                                                jLabel3,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addComponent(
                                                                                jLabel7,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addComponent(jLabel9)
                                                                            .addComponent(
                                                                                jLabel6,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addComponent(
                                                                                jLabel5,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addComponent(
                                                                                jLabel4,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                53,
                                                                                javax.swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addComponent(jLabel11))
                                                                    .addGap(0, 0, 0)))
                                                    .addGap(0, 0, 0)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .LEADING,
                                                                false)
                                                            .addComponent(
                                                                editCourseSeatsInput,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING)
                                                            .addComponent(
                                                                editCourseCollegeCombo1,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                0,
                                                                176,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                editCoruseRoomInput,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING)
                                                            .addComponent(
                                                                editCourseDaysCombo,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                0,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                            .addComponent(
                                                                editCourseTimesCombo,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                0,
                                                                176,
                                                                Short.MAX_VALUE)
                                                            .addGroup(
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                layout
                                                                    .createParallelGroup(
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.LEADING,
                                                                        false)
                                                                    .addComponent(
                                                                        editCourseIDInput,
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.TRAILING,
                                                                        javax.swing.GroupLayout
                                                                            .DEFAULT_SIZE,
                                                                        175,
                                                                        Short.MAX_VALUE)
                                                                    .addComponent(
                                                                        editCourseNameInput,
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.TRAILING)
                                                                    .addComponent(
                                                                        editCourseProfessorInput,
                                                                        javax.swing.GroupLayout
                                                                            .Alignment.TRAILING))
                                                            .addComponent(
                                                                editCourseCollegeCombo,
                                                                javax.swing.GroupLayout.Alignment
                                                                    .TRAILING,
                                                                0,
                                                                javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        addCourseErrorDisplay1,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Course,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_College,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Professor,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_ID,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                23,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Room,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Times,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Days,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Seats,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                addCourseError_Name,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                27,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(
                        jLabel10,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        26,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(
                        jLabel10,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        18,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(422, 422, 422))
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                editCourseCollegeCombo1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(
                                                addCourseError_Course,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                18,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                editCourseCollegeCombo,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(
                                                addCourseError_College,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                20,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                editCourseIDInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(
                                                addCourseError_ID,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                18,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(
                                addCourseErrorDisplay1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                29,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(
                                                addCourseError_Name,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                20,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        editCourseNameInput,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Professor,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                20,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                editCourseProfessorInput,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                    .addGap(10, 10, 10)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Room,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                20,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                editCoruseRoomInput,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Times,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                20,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                editCourseTimesCombo,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Days,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                20,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                editCourseDaysCombo,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(
                                addCourseError_Seats,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                20,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                editCourseSeatsInput,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                    .addGap(5, 5, 5)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        158,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCourseSubmitButton)
                            .addComponent(addCourseCancelButton))
                    .addGap(4, 4, 4)));
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addCourseCancelButton;
  private javax.swing.JLabel addCourseErrorDisplay1;
  private javax.swing.JLabel addCourseError_College;
  private javax.swing.JLabel addCourseError_Course;
  private javax.swing.JLabel addCourseError_Days;
  private javax.swing.JLabel addCourseError_ID;
  private javax.swing.JLabel addCourseError_Name;
  private javax.swing.JLabel addCourseError_Professor;
  private javax.swing.JLabel addCourseError_Room;
  private javax.swing.JLabel addCourseError_Seats;
  private javax.swing.JLabel addCourseError_Times;
  private javax.swing.JTable addCoursePreview;
  private javax.swing.JButton addCourseSubmitButton;
  private javax.swing.JTextField editCoruseRoomInput;
  private javax.swing.JComboBox<String> editCourseCollegeCombo;
  private javax.swing.JComboBox<String> editCourseCollegeCombo1;
  private javax.swing.JComboBox<String> editCourseDaysCombo;
  private javax.swing.JTextField editCourseIDInput;
  private javax.swing.JTextField editCourseNameInput;
  private javax.swing.JTextField editCourseProfessorInput;
  private javax.swing.JTextField editCourseSeatsInput;
  private javax.swing.JComboBox<String> editCourseTimesCombo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
