package coursescheduler;

/** @author evilc */
public class RegistrarPage extends javax.swing.JPanel {
  String page = "REGISTRAR";
  PanelManager controller;

  public void setController(PanelManager input) {
    controller = input;
  }

  public String returnPage() {
    return page;
  }
  /** Creates new form RegistrarPage */
  public RegistrarPage() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    scheduleGeneratorButton = new javax.swing.JButton();
    loadCSVFileButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    currentCoursesTable = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    saveCSVFileButton = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    backToLoginButton = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Registrar");

    scheduleGeneratorButton.setText("Schedule Generator");
    scheduleGeneratorButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            scheduleGeneratorButtonActionPerformed(evt);
          }
        });

    loadCSVFileButton.setText("Load CSV File");
    loadCSVFileButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            loadCSVFileButtonActionPerformed(evt);
          }
        });

    currentCoursesTable.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null},
              {null, null, null, null, null, null, null, null}
            },
            new String[] {
              "College", "ID", "Name", "Professor", "Room(s)", "Times", "Days", "Seats"
            }) {
          boolean[] canEdit = new boolean[] {false, false, false, false, false, true, true, false};

          public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
          }
        });
    jScrollPane1.setViewportView(currentCoursesTable);
    if (currentCoursesTable.getColumnModel().getColumnCount() > 0) {
      currentCoursesTable.getColumnModel().getColumn(7).setResizable(false);
    }

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel2.setText("Current Courses Loaded:");

    saveCSVFileButton.setText("Save as CSV File");
    saveCSVFileButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveCSVFileButtonActionPerformed(evt);
          }
        });

    jButton7.setText("Exit");
    jButton7.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
          }
        });

    backToLoginButton.setText("Back to Login");
    backToLoginButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            backToLoginButtonActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        scheduleGeneratorButton,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        130,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(
                                        loadCSVFileButton,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        130,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(
                                        saveCSVFileButton,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        130,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(
                                        layout
                                            .createSequentialGroup()
                                            .addComponent(backToLoginButton)
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(jButton7))
                                    .addComponent(
                                        jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        657,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                scheduleGeneratorButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                47,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                saveCSVFileButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                47,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                loadCSVFileButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                47,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(77, 77, 77)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        286,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backToLoginButton)
                            .addComponent(jButton7))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  } // </editor-fold>//GEN-END:initComponents

  private void scheduleGeneratorButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_scheduleGeneratorButtonActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_scheduleGeneratorButtonActionPerformed

  private void loadCSVFileButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_loadCSVFileButtonActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_loadCSVFileButtonActionPerformed

  private void saveCSVFileButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_saveCSVFileButtonActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_saveCSVFileButtonActionPerformed

  private void jButton7ActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton7ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jButton7ActionPerformed

  private void backToLoginButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_backToLoginButtonActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_backToLoginButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backToLoginButton;
  private javax.swing.JTable currentCoursesTable;
  private javax.swing.JButton jButton7;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton loadCSVFileButton;
  private javax.swing.JButton saveCSVFileButton;
  private javax.swing.JButton scheduleGeneratorButton;
  // End of variables declaration//GEN-END:variables
}
