/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course_scheduler;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        NewJFrame frame = new NewJFrame();
        String[] test = {"Test"};
        frame.main(test);
    }
}
