/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_scheduler;

/**
 *
 * @author evilc
 */
public class guiFrame extends javax.swing.JFrame {
    LoginPage loginPagePanel = new LoginPage();
    createAccountJpanel createAccountPanel = new createAccountJpanel();
    AddCourseDepartmentChair addCourseDepartmentChairPanel = new AddCourseDepartmentChair();
    AddCoursePageFaculty addCourseFacultyPanel = new AddCoursePageFaculty();
    DepartmentChairPage departmentChairPanel = new DepartmentChairPage();
    RegistrarPage registrarPanel = new RegistrarPage();
    EditCourse editCoursePanel = new EditCourse();
    FacultyPage facultyPanel = new FacultyPage();
    RemoveCoursePage removeCoursePanel = new RemoveCoursePage();
    
    PanelManager controller = new PanelManager(loginPagePanel, createAccountPanel, addCourseDepartmentChairPanel, 
            addCourseFacultyPanel,editCoursePanel, registrarPanel, facultyPanel,
            departmentChairPanel, removeCoursePanel);
    /**
     * Creates new form guiFrame
     */
    public guiFrame() {
        add(loginPagePanel);
        add(createAccountPanel);
        add(addCourseDepartmentChairPanel);
        add(addCourseFacultyPanel);
        add(departmentChairPanel);
        add(registrarPanel);
        add(editCoursePanel);
        add(facultyPanel);
        add(removeCoursePanel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        debugCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("DEBUG:");
        getContentPane().add(jLabel1);

        debugCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOGIN", "CREATE_ACCOUNT", "ADD_COURSE_DEPARTMENT_CHAIR", "ADD_COURSE_FACULTY", "REMOVE_COURSE", "EDIT_COURSE", "SCHEDULE_GENERATOR", "INPUT_FILE", "DEPARTMENT_CHAIR", "FACULTY", "REGISTRAR" }));
        debugCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugComboActionPerformed(evt);
            }
        });
        getContentPane().add(debugCombo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debugComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugComboActionPerformed
        // TODO add your handling code here:
        String nextPage = debugCombo.getSelectedItem().toString();
        controller.switchPage("DEBUG", nextPage);
        
        
        
    }//GEN-LAST:event_debugComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> debugCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
