package course_scheduler;

import java.awt.event.KeyEvent;

public class LoginPage extends javax.swing.JFrame {

  /** Creates new form LoginPage */
  public LoginPage() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    passwordField = new javax.swing.JPasswordField();
    emailField = new javax.swing.JTextField();
    createAccountLabel = new javax.swing.JLabel();
    courseSchedulerTitle = new javax.swing.JLabel();
    emailLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    passwordField.addKeyListener(
        new java.awt.event.KeyAdapter() {
          public void keyPressed(java.awt.event.KeyEvent evt) {
            passwordFieldKeyPressed(evt);
          }
        });

    emailField.addKeyListener(
        new java.awt.event.KeyAdapter() {
          public void keyPressed(java.awt.event.KeyEvent evt) {
            emailFieldKeyPressed(evt);
          }
        });

    createAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    createAccountLabel.setText("create an account");
    createAccountLabel.addMouseListener(
        new java.awt.event.MouseAdapter() {
          public void mouseClicked(java.awt.event.MouseEvent evt) {
            createAccountLabelMouseClicked(evt);
          }
        });

    courseSchedulerTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
    courseSchedulerTitle.setText("Course Scheduler");

    emailLabel.setLabelFor(emailField);
    emailLabel.setText("email");

    passwordLabel.setLabelFor(passwordField);
    passwordLabel.setText("password");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap(408, Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(
                                createAccountLabel,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                200,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(
                                layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(
                                        courseSchedulerTitle,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        204,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(
                                        layout
                                            .createSequentialGroup()
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(passwordLabel)
                                                    .addComponent(emailLabel))
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement
                                                    .UNRELATED)
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        false)
                                                    .addComponent(
                                                        emailField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        132,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                        passwordField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        132,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(418, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap(275, Short.MAX_VALUE)
                    .addComponent(courseSchedulerTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(
                                                emailField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailLabel))
                                    .addGap(32, 32, 32))
                            .addGroup(
                                layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordLabel)
                                    .addComponent(
                                        passwordField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(createAccountLabel)
                    .addContainerGap(252, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void passwordFieldKeyPressed(
      java.awt.event.KeyEvent evt) { // GEN-FIRST:event_passwordFieldKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      // TODO: Trigger login function.
    }
  } // GEN-LAST:event_passwordFieldKeyPressed

  private void emailFieldKeyPressed(
      java.awt.event.KeyEvent evt) { // GEN-FIRST:event_emailFieldKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
      // TODO: Trigger login function.
    }
  } // GEN-LAST:event_emailFieldKeyPressed

  private void createAccountLabelMouseClicked(
      java.awt.event.MouseEvent evt) { // GEN-FIRST:event_createAccountLabelMouseClicked
    // TODO: Transition to AccountCreationPage.
  } // GEN-LAST:event_createAccountLabelMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel courseSchedulerTitle;
  private javax.swing.JLabel createAccountLabel;
  private javax.swing.JTextField emailField;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JPasswordField passwordField;
  private javax.swing.JLabel passwordLabel;
  // End of variables declaration//GEN-END:variables
}
