/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course_scheduler;


import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evilc
 */
public class NewJFrame extends javax.swing.JFrame {
    String password_input = "Test Username";
    String username_input = "Test Password";
    List<NewCourse> allCourses = new ArrayList<NewCourse>(); 

    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        DeanButton1 = new javax.swing.JButton();
        OtherButton1 = new javax.swing.JButton();
        ProfessorButton1 = new javax.swing.JButton();
        ExitButton1 = new javax.swing.JButton();
        PasswordLabel1 = new javax.swing.JLabel();
        Password1 = new javax.swing.JTextField();
        Username1 = new javax.swing.JTextField();
        UsernameLabel1 = new javax.swing.JLabel();
        UsernameLabel2 = new javax.swing.JLabel();
        LoginSubmitButton1 = new javax.swing.JButton();
        LoginReset1 = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        NewScheduleButton1 = new javax.swing.JButton();
        LoadScheduleButton1 = new javax.swing.JButton();
        SettingsButton1 = new javax.swing.JButton();
        BackButton1 = new javax.swing.JButton();
        NewSchedule = new javax.swing.JPanel();
        InputFile1 = new javax.swing.JTextField();
        FileSubmitButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CollegeDisplay1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FilePreview1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Continue1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BackButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ScheduleGenerator = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FilePreview2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        AddCourse_ID = new javax.swing.JTextField();
        AddCourse_Name = new javax.swing.JTextField();
        AddCourse_Professor = new javax.swing.JTextField();
        EditCourse_Submit1 = new javax.swing.JButton();
        EditCourse_Professor = new javax.swing.JTextField();
        EditCourse_Name = new javax.swing.JTextField();
        EditCourse_Times = new javax.swing.JComboBox<>();
        AddCourse_Days = new javax.swing.JComboBox<>();
        EditCourse_Days = new javax.swing.JComboBox<>();
        AddCourse_Times = new javax.swing.JComboBox<>();
        EditCourse_ChooseID = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RemoveCourse_ChooseID1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        RemoveCourseButton1 = new javax.swing.JButton();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        Error4 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        Error5 = new javax.swing.JLabel();
        Error6 = new javax.swing.JLabel();
        Error7 = new javax.swing.JLabel();
        Error8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setToolTipText("");

        DeanButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeanButton1.setText("Dean");
        DeanButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeanButton1.setDefaultCapable(false);
        DeanButton1.setFocusPainted(false);
        DeanButton1.setEnabled(false);
        DeanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeanButton1ActionPerformed(evt);
            }
        });

        OtherButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OtherButton1.setText("Other");
        OtherButton1.setEnabled(false);
        OtherButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherButton1ActionPerformed(evt);
            }
        });

        ProfessorButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProfessorButton1.setText("Professor");
        ProfessorButton1.setEnabled(false);
        ProfessorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorButton1ActionPerformed(evt);
            }
        });

        ExitButton1.setText("Exit");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });

        PasswordLabel1.setText("Password");

        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });

        Username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username1ActionPerformed(evt);
            }
        });

        UsernameLabel1.setText("Username");

        UsernameLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsernameLabel2.setText("Login");

        LoginSubmitButton1.setText("Submit");
        LoginSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitButton1ActionPerformed(evt);
            }
        });

        LoginReset1.setText("Reset");
        LoginReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton1))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(UsernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LoginLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProfessorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoginSubmitButton1))
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(OtherButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(LoginLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(LoginReset1)))))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(UsernameLabel2)
                .addGap(48, 48, 48)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel1))
                .addGap(26, 26, 26)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel1))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginSubmitButton1)
                    .addComponent(LoginReset1))
                .addGap(37, 37, 37)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeanButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfessorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtherButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(ExitButton1)
                .addContainerGap())
        );

        getContentPane().add(Login, "card2");

        NewScheduleButton1.setText("New Schedule");
        NewScheduleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewScheduleButton1ActionPerformed(evt);
            }
        });

        LoadScheduleButton1.setText("Load Schedule");
        LoadScheduleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadScheduleButton1ActionPerformed(evt);
            }
        });

        SettingsButton1.setText("Settings");
        SettingsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButton1ActionPerformed(evt);
            }
        });

        BackButton1.setText("Back");
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton1)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(NewScheduleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoadScheduleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SettingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewScheduleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoadScheduleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(BackButton1)
                .addContainerGap())
        );

        getContentPane().add(Menu, "card3");

        FileSubmitButton1.setText("Submit");

        jLabel1.setText("Input File Destination:");

        CollegeDisplay1.setEditable(false);

        FilePreview1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Professor", "Times", "Days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FilePreview1);
        if (FilePreview1.getColumnModel().getColumnCount() > 0) {
            FilePreview1.getColumnModel().getColumn(0).setResizable(false);
            FilePreview1.getColumnModel().getColumn(1).setResizable(false);
            FilePreview1.getColumnModel().getColumn(2).setResizable(false);
            FilePreview1.getColumnModel().getColumn(3).setResizable(false);
            FilePreview1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("College:");

        Continue1.setText("Continue");
        Continue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("File Input");

        BackButton2.setText("Back");
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("<Text here for read errors>");

        javax.swing.GroupLayout NewScheduleLayout = new javax.swing.GroupLayout(NewSchedule);
        NewSchedule.setLayout(NewScheduleLayout);
        NewScheduleLayout.setHorizontalGroup(
            NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewScheduleLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewScheduleLayout.createSequentialGroup()
                        .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewScheduleLayout.createSequentialGroup()
                                .addComponent(CollegeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewScheduleLayout.createSequentialGroup()
                                .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(NewScheduleLayout.createSequentialGroup()
                                        .addComponent(InputFile1)
                                        .addGap(18, 18, 18)
                                        .addComponent(FileSubmitButton1))
                                    .addGroup(NewScheduleLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Continue1)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35))))
                    .addGroup(NewScheduleLayout.createSequentialGroup()
                        .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackButton2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        NewScheduleLayout.setVerticalGroup(
            NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewScheduleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileSubmitButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollegeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NewScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continue1)
                    .addComponent(BackButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(NewSchedule, "card4");

        FilePreview2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Professor", "Times", "Days"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FilePreview2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                FilePreview2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(FilePreview2);
        if (FilePreview2.getColumnModel().getColumnCount() > 0) {
            FilePreview2.getColumnModel().getColumn(0).setResizable(false);
            FilePreview2.getColumnModel().getColumn(1).setResizable(false);
            FilePreview2.getColumnModel().getColumn(2).setResizable(false);
            FilePreview2.getColumnModel().getColumn(3).setResizable(false);
            FilePreview2.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Add Course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EditCourse_Submit1.setText("Submit");
        EditCourse_Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCourse_Submit1ActionPerformed(evt);
            }
        });

        EditCourse_Times.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time 1", "Time 2", "Time 3", "Time 4" }));

        AddCourse_Days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M, W", "M, W, F", "T, TH", " " }));

        EditCourse_Days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M, W", "M, W, F", "T, TH", " " }));

        AddCourse_Times.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time 1", "Time 2", "Time 3", "Time 4" }));

        EditCourse_ChooseID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Edit Course:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Add Course:");

        jLabel7.setText("Course ID:");

        jLabel8.setText("Course Name:");

        jLabel9.setText("Professor:");

        jLabel10.setText("Times:");

        jLabel11.setText("Days");

        jLabel12.setText("Days");

        jLabel13.setText("Times:");

        jLabel14.setText("Professor:");

        jLabel15.setText("Course Name:");

        jLabel16.setText("Course ID:");

        RemoveCourse_ChooseID1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Remove Course:");

        RemoveCourseButton1.setText("Remove");
        RemoveCourseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCourseButton1ActionPerformed(evt);
            }
        });

        Error1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Error1.setForeground(new java.awt.Color(204, 0, 51));

        Error2.setForeground(new java.awt.Color(204, 0, 0));

        Error4.setForeground(new java.awt.Color(204, 0, 51));

        Error3.setForeground(new java.awt.Color(204, 0, 0));

        Error5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Error5.setForeground(new java.awt.Color(204, 0, 51));

        Error6.setForeground(new java.awt.Color(204, 0, 0));

        Error7.setForeground(new java.awt.Color(204, 0, 0));

        Error8.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout ScheduleGeneratorLayout = new javax.swing.GroupLayout(ScheduleGenerator);
        ScheduleGenerator.setLayout(ScheduleGeneratorLayout);
        ScheduleGeneratorLayout.setHorizontalGroup(
            ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddCourse_Days, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCourse_Times, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCourse_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCourse_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCourse_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditCourse_Submit1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EditCourse_Days, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCourse_Times, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCourse_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCourse_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditCourse_ChooseID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveCourseButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemoveCourse_ChooseID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(Error8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleGeneratorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleGeneratorLayout.createSequentialGroup()
                        .addComponent(Error5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleGeneratorLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        ScheduleGeneratorLayout.setVerticalGroup(
            ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScheduleGeneratorLayout.createSequentialGroup()
                        .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleGeneratorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Error5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(AddCourse_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(EditCourse_ChooseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveCourse_ChooseID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error2)
                    .addComponent(Error6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RemoveCourseButton1)
                    .addComponent(EditCourse_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(AddCourse_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Error3)
                    .addComponent(Error7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EditCourse_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(AddCourse_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error4)
                    .addComponent(Error8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(AddCourse_Times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(EditCourse_Times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(AddCourse_Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(EditCourse_Days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(ScheduleGeneratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditCourse_Submit1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(ScheduleGenerator, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int findCourseIndex(String input)
    {
        int index = -1;
        if (allCourses.size() > 0)
        {
            for (int i = 0; i < allCourses.size(); i++)
            {
                if ((input) == (allCourses.get(i).returnCourseID()))
                {
                    index = i;
                    i = allCourses.size() + 1;
                }
            }
        }
        return index;
    }
    
    
    private void DeanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeanButton1ActionPerformed
        // TODO add your handling code here:
        Login.hide();
        Menu.show();
    }//GEN-LAST:event_DeanButton1ActionPerformed

    private void OtherButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherButton1ActionPerformed
        // TODO add your handling code here:
        Login.hide();
        Menu.show();
    }//GEN-LAST:event_OtherButton1ActionPerformed

    private void ProfessorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorButton1ActionPerformed
        // TODO add your handling code here:
        Login.hide();
        Menu.show();
    }//GEN-LAST:event_ProfessorButton1ActionPerformed

    private void LoadScheduleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadScheduleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadScheduleButton1ActionPerformed

    private void SettingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsButton1ActionPerformed

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        // TODO add your handling code here:
        Login.show();
        Menu.hide();
        ProfessorButton1.setEnabled(false);
        DeanButton1.setEnabled(false);
        OtherButton1.setEnabled(false);
        Password1.setText("");
        Username1.setText("");
        Password1.setEditable(true);
        Username1.setEditable(true);
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void Username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username1ActionPerformed

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1ActionPerformed

    private void LoginSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitButton1ActionPerformed
        // TODO add your handling code here:
        password_input = Password1.getText();
        username_input = Username1.getText();
        Password1.setEditable(false);
        Username1.setEditable(false);
        ProfessorButton1.setEnabled(true);
        DeanButton1.setEnabled(true);
        OtherButton1.setEnabled(true);
    }//GEN-LAST:event_LoginSubmitButton1ActionPerformed

    private void LoginReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginReset1ActionPerformed
        // TODO add your handling code here:
        Password1.setText("");
        Username1.setText("");
        Password1.setEditable(true);
        Username1.setEditable(true);
        ProfessorButton1.setEnabled(false);
        DeanButton1.setEnabled(false);
        OtherButton1.setEnabled(false);
    }//GEN-LAST:event_LoginReset1ActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButton1ActionPerformed

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        // TODO add your handling code here:
        NewSchedule.hide();
        Menu.show();
    }//GEN-LAST:event_BackButton2ActionPerformed

    private void NewScheduleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewScheduleButton1ActionPerformed
        // TODO add your handling code here:
        Menu.hide();
        NewSchedule.show();
    }//GEN-LAST:event_NewScheduleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean invalidID = false;
        String courseID_input = AddCourse_ID.getText();
        for (int i = 0; i < allCourses.size(); i++)
        {
            if (courseID_input.equals(allCourses.get(i).returnCourseID()))
            {
                Error1.setText("Course ID already in use.");
                Error2.setText("*");
                invalidID = true;
                i = allCourses.size() + 1;
            }
        }
        
        if (" ".equals(AddCourse_ID.getText()) || "".equals(AddCourse_ID.getText()))
        {
            Error1.setText("Field(s) cannot be blank.");
            Error2.setText("*");
            invalidID = true;
             if (" ".equals(AddCourse_Name.getText()) || "".equals(AddCourse_Name.getText()))
            {
                Error3.setText("*");
            }
            else
            {
                 Error3.setText("");
            }
            
            if (" ".equals(AddCourse_Professor.getText()) || "".equals(AddCourse_Professor.getText()))
            {
                Error4.setText("*");
            }
            else
            {
                Error4.setText("");
            }
        }
        
        
        if (!invalidID)
        {
            Error2.setText("");
            boolean invalidName = false;
            boolean invalidProfessor = false;
            Error1.setText("");
            String professor_input = "";
            String courseName_input = "";
            if (" ".equals(AddCourse_Name.getText()) || "".equals(AddCourse_Name.getText()))
            {
                invalidName = true;
                Error1.setText("Field(s) cannot be blank.");
                Error3.setText("*");
            }
            else
            {
                Error3.setText("");
            }
            
            if (" ".equals(AddCourse_Professor.getText()) || "".equals(AddCourse_Professor.getText()))
            {
                invalidProfessor = true;
                Error1.setText("Field(s) cannot be blank.");
                Error4.setText("*");
            }
            else
            {
                Error4.setText("");
            }
            
            if (!invalidName && !invalidProfessor)
            {
                Error3.setText("");
                Error4.setText("");
                courseName_input = AddCourse_Name.getText();
                professor_input = AddCourse_Professor.getText();
                String times_input = AddCourse_Times.getSelectedItem().toString();
                String days_input = AddCourse_Days.getSelectedItem().toString();
                Object[] newCourse = {courseID_input, courseName_input, professor_input, times_input, days_input};
                DefaultTableModel model = (DefaultTableModel) FilePreview2.getModel();
                int numRows = model.getRowCount();
                for (int i = 0; i < numRows; i++)
                {
                    if (model.getValueAt(i, 0) == null)
                    {
                        model.setValueAt(courseID_input, i, 0);
                        model.setValueAt(courseName_input, i, 1);
                        model.setValueAt(professor_input, i, 2);
                        model.setValueAt(times_input, i, 3);
                        model.setValueAt(days_input, i, 4);
                        i = numRows;
                    }
                    else if (i == (numRows - 1))
                    {
                        model.addRow(newCourse);
                    }
                }
                EditCourse_ChooseID.addItem(courseID_input);
                RemoveCourse_ChooseID1.addItem(courseID_input);
                NewCourse temp_course = new NewCourse();
                temp_course.setVariables(courseID_input, courseName_input, professor_input, times_input, days_input);
                allCourses.add(temp_course);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void EditCourse_Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCourse_Submit1ActionPerformed
        // TODO add your handling code here:
        String tempID = "";
        int index = -1;
        if ((EditCourse_ChooseID.getSelectedItem().toString()) != "Select Course")
        {
            tempID = EditCourse_ChooseID.getSelectedItem().toString();
            index = findCourseIndex(tempID);
        }
        else
        {
            Error5.setText("Course ID cannot be blank.");
            Error6.setText("*");
        }
        
        if (index != -1)
        {
            Error5.setText("");
            Error6.setText("");
            String tempName = "";
            String tempProfessor = "";
            boolean invalidName = false;
            boolean invalidProfessor = false;
            if (" ".equals(EditCourse_Name.getText()) || "".equals(EditCourse_Name.getText()))
            {
               Error5.setText("Field(s) cannot be blank.");
               Error7.setText("*");
               invalidName = true;
            }

            
            if (" ".equals(EditCourse_Professor.getText()) || "".equals(EditCourse_Professor.getText()))
            {
                Error5.setText("Field(s) cannot be blank.");
                Error8.setText("*");
                invalidProfessor = true;
            }

            
            if (!invalidName && !invalidProfessor)
            {
                Error5.setText("");
                Error6.setText("");
                Error7.setText("");
                Error8.setText("");
                String times_input = EditCourse_Times.getSelectedItem().toString();
                String days_input = EditCourse_Days.getSelectedItem().toString();
                tempName = EditCourse_Name.getText();
                tempProfessor = EditCourse_Professor.getText();
                allCourses.get(index).setVariables(tempID, tempName, tempProfessor, EditCourse_Times.getSelectedItem().toString() , EditCourse_Days.getSelectedItem().toString());
                DefaultTableModel model = (DefaultTableModel) FilePreview2.getModel();
                int numRows = model.getRowCount();
                for (int i = 0; i < numRows; i++)
                {
                    if (model.getValueAt(i, 0) == tempID)
                    {
                        model.setValueAt(tempName, i, 1);
                        model.setValueAt(tempProfessor, i, 2);
                        model.setValueAt(times_input, i, 3);
                        model.setValueAt(days_input, i, 4);
                        i = numRows + 1;
                    }
                }
            }

        }
        
    }//GEN-LAST:event_EditCourse_Submit1ActionPerformed

    private void FilePreview2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_FilePreview2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_FilePreview2AncestorAdded

    private void Continue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue1ActionPerformed
        // TODO add your handling code here:
        NewSchedule.hide();
        ScheduleGenerator.show();
    }//GEN-LAST:event_Continue1ActionPerformed

    private void RemoveCourseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCourseButton1ActionPerformed
        // TODO add your handling code here:
        String removeCourseID = "";
        int index = -1;
        if ((RemoveCourse_ChooseID1.getSelectedItem().toString()) != "Select Course")
        {
            removeCourseID = RemoveCourse_ChooseID1.getSelectedItem().toString();
            index = findCourseIndex(removeCourseID);
        }
        
        if (index != -1)
        {
            allCourses.remove(index);
            EditCourse_ChooseID.removeItem(removeCourseID);
            RemoveCourse_ChooseID1.removeItem(removeCourseID);
            DefaultTableModel model = (DefaultTableModel) FilePreview2.getModel();
            int numRows = model.getRowCount();
            boolean allValuesFilled = false;
            for (int i = 0; i < numRows; i++)
            {
                if (model.getValueAt(i, 0) == removeCourseID)
                {
                    model.removeRow(i);
                    i = numRows + 1;
                }
            }
        
        }
        
        
        
    }//GEN-LAST:event_RemoveCourseButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddCourse_Days;
    private javax.swing.JTextField AddCourse_ID;
    private javax.swing.JTextField AddCourse_Name;
    private javax.swing.JTextField AddCourse_Professor;
    private javax.swing.JComboBox<String> AddCourse_Times;
    private javax.swing.JButton BackButton1;
    private javax.swing.JButton BackButton2;
    private javax.swing.JTextField CollegeDisplay1;
    private javax.swing.JButton Continue1;
    private javax.swing.JButton DeanButton1;
    private javax.swing.JComboBox<String> EditCourse_ChooseID;
    private javax.swing.JComboBox<String> EditCourse_Days;
    private javax.swing.JTextField EditCourse_Name;
    private javax.swing.JTextField EditCourse_Professor;
    private javax.swing.JButton EditCourse_Submit1;
    private javax.swing.JComboBox<String> EditCourse_Times;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JLabel Error4;
    private javax.swing.JLabel Error5;
    private javax.swing.JLabel Error6;
    private javax.swing.JLabel Error7;
    private javax.swing.JLabel Error8;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JTable FilePreview1;
    private javax.swing.JTable FilePreview2;
    private javax.swing.JButton FileSubmitButton1;
    private javax.swing.JTextField InputFile1;
    private javax.swing.JButton LoadScheduleButton1;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginReset1;
    private javax.swing.JButton LoginSubmitButton1;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel NewSchedule;
    private javax.swing.JButton NewScheduleButton1;
    private javax.swing.JButton OtherButton1;
    private javax.swing.JTextField Password1;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JButton ProfessorButton1;
    private javax.swing.JButton RemoveCourseButton1;
    private javax.swing.JComboBox<String> RemoveCourse_ChooseID1;
    private javax.swing.JPanel ScheduleGenerator;
    private javax.swing.JButton SettingsButton1;
    private javax.swing.JTextField Username1;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JLabel UsernameLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
