package course_scheduler;

import coursescheduler.PanelManager;

/** @author evilc */
public class RemoveCoursePage extends javax.swing.JPanel {
  String page = "REMOVE_COURSE";
  coursescheduler.PanelManager controller;

  public void setController(PanelManager input) {
    controller = input;
  }

  public String returnPage() {
    return page;
  }

  public RemoveCoursePage() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    removeCourseSubmitButton = new javax.swing.JButton();
    removeCourseCombo = new javax.swing.JComboBox<>();
    removeCourseCancelButon = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel1.setText("Remove Course");

    removeCourseSubmitButton.setText("Submit");

    removeCourseCombo.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Course"}));

    removeCourseCancelButon.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(54, 54, 54)
                                    .addComponent(
                                        removeCourseCombo,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(removeCourseCancelButon)
                                    .addGap(107, 107, 107)
                                    .addComponent(removeCourseSubmitButton)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(
                                        removeCourseCombo,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeCourseCancelButon)
                            .addComponent(removeCourseSubmitButton))
                    .addContainerGap(33, Short.MAX_VALUE)));
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton removeCourseCancelButon;
  private javax.swing.JComboBox<String> removeCourseCombo;
  private javax.swing.JButton removeCourseSubmitButton;
  // End of variables declaration//GEN-END:variables
}
