/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course_scheduler;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {}
}
